apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "09"
spec:
  project: system
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: "1.*"

    helm:
      releaseName: longhorn

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
