apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: system
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "9.*"

    helm:
      releaseName: traefik

      values: |
        image:
          name: valerauko/traefa
          tag: "2.4.8-32e08f35"
        deployment:
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "9100"
        additionalArguments:
          - "--certificatesresolvers.letsencrypt.acme.email={{ .Values.email }}"
          - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
          - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
          - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=httpreq"
          - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=60"
          - "--experimental.http3=true"
          - "--entrypoints.websecure.enablehttp3=true"
        env:
          - name: HTTPREQ_ENDPOINT
            value: http://panther.kube-system.svc.cluster.local
        persistence:
          enabled: true
          size: 32Mi
          storageClass: longhorn
        ports:
          web:
            redirectTo: websecure
          websecure:
            tls:
              enabled: true
              certResolver: letsencrypt
              domains:
                - main: "*.{{ .Values.domain }}"
                  sans:
                    - "{{ .Values.domain }}"
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
            namespaces:
              - argo-cd
              - default
              - monitoring
        logs:
          general:
            level: INFO
          access:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
