apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "05"
spec:
  description: System stuff

  sourceRepos:
  - '*'

  destinations:
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: argo-cd
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: 'policy'
    kind: PodSecurityPolicy
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'storage.k8s.io'
    kind: StorageClass
  - group: 'storage.k8s.io'
    kind: CSIDriver
