apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: panther
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: system
  source:
    repoURL: https://github.com/valerauko/panther
    targetRevision: master
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
