name: Release example Docker image

on:
  push:
    paths: "example/**"
    branches: [ main, feature/example ]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        id: build-image
        working-directory: example
        run: |
          set -euo pipefail
          image=valerauko/rokalyuk:$(git rev-parse --short HEAD)
          docker build -t "$image" .
          echo "::set-output name=image::$image"
      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | \
          docker login ghcr.io -u valerauko --password-stdin
      - name: Push Docker image
        run: |
          set -euo pipefail
          image=${{ steps.build-image.outputs.image }}
          docker tag "$image" "ghcr.io/$image"
          docker -D push "ghcr.io/$image"
  update-manifests:
    runs-on: ubuntu-latest
    needs: create-docker-image
    steps:
      - uses: actions/checkout@v2
      - name: Update manifests
        working-directory: example/k8s
        run: |
          sed -i -r -e "s/rokalyuk:\w+/rokalyuk:$(git rev-parse --short HEAD)/i" deployment.yaml
      - name: Commit update
        run: |
          git config user.email "actions@github.com" && \
          git config user.name "Github Action" && \
          git add example/k8s/deployment.yaml && \
          git commit -m "Update target image tag" && \
          git push
