name: Follow upstream repo
on:
  push:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  build-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out upstream
        run: git clone https://github.com/traefik/traefik
      - name: Compare commit hash
        id: commit-check
        run: |
          set -euo pipefail
          current=$(sed -nr 's/\s+tag: ".+-(\w+)"/\1/p' apps/11-traefik.yaml)
          cd traefik
          latest=$(git rev-parse --short HEAD)
          different=$([ "$current" == "$latest" ] && echo 'false' || echo 'true')
          echo "Currently deployed: $current. Latest: $latest. Are they different? $different"
          echo "::set-output name=upstream::$latest"
          echo "::set-output name=updated::$different"
          cd -
      - name: Build Docker image
        if: steps.commit-check.outputs.updated == 'true'
        id: build-image
        run: |
          set -euo pipefail
          cd traefik
          last_tag=$(git describe --abbrev=0 --tags | cut -c2-)
          new_tag="$last_tag-${{ steps.commit-check.outputs.upstream }}"
          make build-image
          new_image="valerauko/traefa:$new_tag"
          echo "::set-output name=new-image::$new_image"
          echo "::set-output name=new-tag::$new_tag"
          docker tag traefik/traefik:latest "$new_image"
          cd -
      - name: Login to Docker Hub
        if: steps.commit-check.outputs.updated == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        if: steps.commit-check.outputs.updated == 'true'
        run: docker push ${{ steps.build-image.outputs.new-image }}
      - name: Update manifest
        if: steps.commit-check.outputs.updated == 'true'
        run: |
          sed -i -r -e "s/tag: \".*\"/tag: \"${{ steps.build-image.outputs.new-tag }}\"/i" apps/11-traefik.yaml
      - name: Commit latest release version
        if: steps.commit-check.outputs.updated == 'true'
        run: |
          set -euo pipefail
          git config --global user.name 'Github Action'
          git config --global user.email 'actions@github.com'
          git add apps/11-traefik.yaml
          git commit -m "Update Traefik image"
          git push
